/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : cik1
**     Processor : MC9S12NE64CPV
**     Component : MC9S12NE64_112
**     Version   : Component 02.001, Driver 02.06, CPU db: 2.87.134
**     Datasheet : MC9S12NE64V1 Rev. 1.1 06/2006
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2017-03-06, 16:35
**     Abstract  :
**         This component "MC9S12NE64_112" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "A0.h"
#include "sw1.h"
#include "A1.h"
#include "TI1.h"
#include "leds.h"
#include "SCI2.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x0CFFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(Cpu_Interrupt)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12NE64_112)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 25MHz,
     *   - possible                   : 2500 c, 100000 ns
     *   - without removable overhead : 2497 c, 99880 ns
     */
    pshd                               /* (2 c: 80 ns) backup D */
    ldd #$033E                         /* (2 c: 80 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 120 ns) repeat 830x */
    puld                               /* (3 c: 120 ns) restore D */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12NE64_112)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12NE64_112)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12NE64_112)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12NE64_112)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12NE64_112)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma CODE_SEG __NEAR_SEG NON_BANKED

#define INITRG_ADR  0x11U              /* Register map position register */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{
  /* ### MC9S12NE64_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Initialization of the registers INITRG, INITRM, INITEE is done to protect them to be written accidentally later by the application */
  /*lint -save  -e950 -e923 Disable MISRA rule (1.1,11.3) checking. */
  *(byte*)INITRG_ADR = 0x00U;          /* Set the register map position */
  asm("nop");                          /* nop instruction */
  /*lint -restore Enable MISRA rule (1.1,11.3) checking. */
  /* INITRM: RAM15=0,RAM14=0,RAM13=1,RAM12=0,RAM11=1,??=0,??=0,RAMHAL=1 */
  setReg8(INITRM, 0x29U);              /* Set the RAM map position */ 
  /* MISC: ??=0,??=0,??=0,??=0,EXSTR1=1,EXSTR0=1,ROMHM=0,ROMON=1 */
  setReg8(MISC, 0x0DU);                 
  /* PEAR: NOACCE=0,??=0,PIPOE=0,NECLK=1,LSTRE=0,RDWE=0,??=0,??=0 */
  setReg8(PEAR, 0x10U);                 
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,SYSWAI=0,ROAWAI=0,PLLWAI=0,CWAI=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xB1U);              /* Disable the PLL */ 
  /* SYNR: ??=0,??=0,SYN5=0,SYN4=0,SYN3=0,SYN2=0,SYN1=0,SYN0=0 */
  setReg8(SYNR, 0x00U);                /* Set the multiplier register */ 
  /* REFDV: ??=0,??=0,??=0,??=0,REFDV3=0,REFDV2=0,REFDV1=0,REFDV0=0 */
  setReg8(REFDV, 0x00U);               /* Set the divider register */ 
  /* PLLCTL: CME=1,PLLON=1,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xF1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12NE64_112)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* PORTA: BIT1=1,BIT0=1 */
  setReg8Bits(PORTA, 0x03U);            
  /* PUCR: PUPAE=0 */
  clrReg8Bits(PUCR, 0x01U);             
  /* DDRA: BIT1=1,BIT0=1 */
  setReg8Bits(DDRA, 0x03U);             
  /* PIEH: PIEH6=0 */
  clrReg8Bits(PIEH, 0x40U);             
  /* PPSH: PPSH6=0 */
  clrReg8Bits(PPSH, 0x40U);             
  /* PERH: PERH6=1 */
  setReg8Bits(PERH, 0x40U);             
  /* DDRH: DDRH6=0 */
  clrReg8Bits(DDRH, 0x40U);             
  /* TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0 */
  clrReg8Bits(TSCR1, 0xF0U);            
  /* PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(PACTL, 0x0CU);            
  /* OC7M: OC7M4=0 */
  clrReg8Bits(OC7M, 0x10U);             
  /* TIOS: IOS7=1,IOS4=1 */
  setReg8Bits(TIOS, 0x90U);             
  /* TCTL1: OM7=0,OL7=0,OM4=0,OL4=0 */
  clrReg8Bits(TCTL1, 0xC3U);            
  /* TTOV: TOV7=0,TOV4=0 */
  clrReg8Bits(TTOV, 0x90U);             
  /* TSCR2: TOI=0,TCRE=1,PR2=1,PR1=1,PR0=0 */
  clrSetReg8Bits(TSCR2, 0x81U, 0x0EU);  
  /* TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,??=1,??=1,??=1,??=1 */
  setReg8(TFLG1, 0xFFU);                
  /* TIE: C4I=1 */
  setReg8Bits(TIE, 0x10U);              
  /* PTL: PTL6=0,PTL5=0,PTL4=0,PTL3=0,PTL2=0,PTL1=0,PTL0=0 */
  clrReg8Bits(PTL, 0x7FU);              
  /* WOML: WOML6=0,WOML5=0,WOML4=0,WOML3=0,WOML2=0,WOML1=0,WOML0=0 */
  clrReg8Bits(WOML, 0x7FU);             
  /* DDRL: DDRL6=1,DDRL5=1,DDRL4=1,DDRL3=1,DDRL2=1,DDRL1=1,DDRL0=1 */
  setReg8Bits(DDRL, 0x7FU);             
  /* WOMS: WOMS1=0 */
  clrReg8Bits(WOMS, 0x02U);             
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* COPCTL: WCOP=0,RSBCK=0,??=0,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0x00U);               
  /* RDRIV: RDPK=0,RDPE=0,RDPB=0,RDPA=0 */
  clrReg8Bits(RDRIV, 0x93U);            
  /* RDRH: RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  clrReg8Bits(RDRH, 0x7FU);             
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ3=0,RDRJ2=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xCFU);             
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0 */
  clrReg8Bits(RDRT, 0xF0U);             
  /* RDRL: RDRL6=0,RDRL5=0,RDRL4=0,RDRL3=0,RDRL2=0,RDRL1=0,RDRL0=0 */
  clrReg8Bits(RDRL, 0x7FU);             
  /* RDRG: RDRG7=0,RDRG6=0,RDRG5=0,RDRG4=0,RDRG3=0,RDRG2=0,RDRG1=0,RDRG0=0 */
  setReg8(RDRG, 0x00U);                 
  /* INTCR: IRQEN=0 */
  clrReg8Bits(INTCR, 0x40U);            
  /* ### MC9S12NE64_112 "Cpu" init code ... */
  /* ### BitIO "A0" init code ... */
  /* ### BitIO "sw1" init code ... */
  /* ### BitIO "A1" init code ... */
  /* ### TimerInt "TI1" init code ... */
  /* TC4: BIT15=1,BIT14=0,BIT13=0,BIT12=1,BIT11=1,BIT10=0,BIT9=0,BIT8=0,BIT7=1,BIT6=0,BIT5=0,BIT4=1,BIT3=0,BIT2=1,BIT1=1,BIT0=0 */
  setReg16(TC4, 0x9896U);              /* Store given value to the compare register */ 
  /* TC7: BIT15=1,BIT14=0,BIT13=0,BIT12=1,BIT11=1,BIT10=0,BIT9=0,BIT8=0,BIT7=1,BIT6=0,BIT5=0,BIT4=1,BIT3=0,BIT2=1,BIT1=1,BIT0=0 */
  setReg16(TC7, 0x9896U);              /* Store given value to the modulo register */ 
  /* ### BitsIO "leds" init code ... */
  /* ### Init_SCI "SCI2" init code ... */
  SCI2_Init();
  /* Common peripheral initialization - ENABLE */
  /* TSCR1: TEN=1 */
  setReg8Bits(TSCR1, 0x80U);            
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
