/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : RTC.h
**     Project     : test_101v
**     Processor   : MC9S08QE16CLC
**     Component   : Init_RTC
**     Version     : Component 01.063, Driver 01.11, CPU db: 3.00.027
**     Compiler    : CodeWarrior HCS08 C Compiler
**     Date/Time   : 2017-05-16, 20:34, # CodeGen: 20
**     Abstract    :
**          This file implements the Real Time Clock (RTC)
**          module initialization according to the Peripheral 
**          Initialization Component settings, and defines interrupt service 
**          routines prototypes.
**     Settings    :
**          Component name                                 : RTC
**          Device                                         : RTC
**          Settings                                       : 
**            Clock settings                               : 
**              Clock select                               : 1-kHz low power oscillator
**              Prescaler                                  : 1000
**              RTC modulo value                           : 1
**              Period                                     : 2 s
**          Interrupts                                     : 
**            Interrupt                                    : Vrtc
**            RTC Interrupt                                : Enabled
**            ISR name                                     : rtc_isr
**          Initialization                                 : 
**            Call Init method                             : yes
**     Contents    :
**         Init - void RTC_Init(void);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file RTC.h
** @version 01.11
** @brief
**          This file implements the Real Time Clock (RTC)
**          module initialization according to the Peripheral 
**          Initialization Component settings, and defines interrupt service 
**          routines prototypes.
*/         
/*!
**  @addtogroup RTC_module RTC module documentation
**  @{
*/         

#ifndef __RTC
#define __RTC

/* MODULE RTC. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"




/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see RTC.c file for more information).
** ===================================================================
*/
__interrupt void rtc_isr(void);

void RTC_Init(void);
/*
** ===================================================================
**     Method      :  RTC_Init (component Init_RTC)
**     Description :
**         This method initializes registers of the RTC module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END RTC. */

#endif
/* ifndef __RTC */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
