/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace/grace_2_20_02_32/packages/ti/mcu/msp430/csl2/communication/EUSCI_init.xdt
 */
#include <stdint.h>
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/eusci_b_spi.h>

/* USER CODE START (section: EUSCI_B0_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: EUSCI_B0_init_c_prologue) */

/*
 *  ======== EUSCI_B0_graceInit ========
 *  Initialize Config for the MSP430 EUSCI_B0
 */
void EUSCI_B0_graceInit(void)
{

    /* USER CODE START (section: EUSCI_B0_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: EUSCI_B0_graceInit_prologue) */

    /* USER CODE START (section: EUSCI_B0_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: EUSCI_B0_graceInit_epilogue) */

}
