/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace/grace_2_20_02_32/packages/ti/mcu/msp430/csl2/frctl/FRCTL_init.xdt
 */
#include <driverlib/MSP430FR5xx_6xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR5xx_6xx/fram.h>

/* USER CODE START (section: FRCTL_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: FRCTL_init_c_prologue) */

/*
 *  ======== FRCTL_graceInit ========
 *  Initialize Config for the MSP430 FRCTL
 */
void FRCTL_graceInit(void)
{
    /* USER CODE START (section: FRCTL_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: FRCTL_graceInit_prologue) */

    /* Configure the wait state control of the FRAM module */
    FRAM_configureWaitStateControl(FRAM_BASE,
                                   FRAM_ACCESS_TIME_CYCLES_0);


    /* USER CODE START (section: FRCTL_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: FRCTL_graceInit_epilogue) */
}

