/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : Project_2
**     Processor : MC9S12NE64CPV
**     Component : MC9S12NE64_112
**     Version   : Component 02.001, Driver 02.06, CPU db: 2.87.134
**     Datasheet : MC9S12NE64V1 Rev. 1.1 06/2006
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2017-03-27, 17:06
**     Abstract  :
**         This component "MC9S12NE64_112" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         SetIntVect  - byte Cpu_SetIntVect(word VectNo, void* ProcAddr);
**         GetIntVect  - byte Cpu_GetIntVect(word VectNo, void* *ProcAddr);
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**         Delay100US  - void Cpu_Delay100US(word us100);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "leds.h"
#include "rgbled.h"
#include "sw1.h"
#include "uart0.h"
#include "ADC1.h"
#include "slow_timer.h"
#include "fast_timer.h"
#include "rf_ce.h"
#include "rf_nss.h"
#include "rf_irq.h"
#include "SPI1.h"
#include "Events.h"
#include "Cpu.h"

#define CGM_DELAY  0x0CFFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */

/* Forward declaration of the interrupt routines for unhandled interrupts */
void Cpu_Interrupt(void);

/* Interrupt routines for interrupts in RAM */
/*lint -save  -e923 Disable MISRA rule (11.3) checking. */
tIntFunc IntTable[] = {                /* Addresses of interrupt routines */
  Cpu_Interrupt,                        /*0x3F  0xFF80   1  ivVReserved63 unused by PE */
  Cpu_Interrupt,                        /*0x3E  0xFF82   1  ivVReserved62 unused by PE */
  Cpu_Interrupt,                        /*0x3D  0xFF84   1  ivVReserved61 unused by PE */
  Cpu_Interrupt,                        /*0x3C  0xFF86   1  ivVReserved60 unused by PE */
  Cpu_Interrupt,                        /*0x3B  0xFF88   1  ivVReserved59 unused by PE */
  Cpu_Interrupt,                        /*0x3A  0xFF8A   1  ivVReserved58 unused by PE */
  Cpu_Interrupt,                        /*0x39  0xFF8C   1  ivVReserved57 unused by PE */
  Cpu_Interrupt,                        /*0x38  0xFF8E   1  ivVReserved56 unused by PE */
  Cpu_Interrupt,                        /*0x37  0xFF90   1  ivVReserved55 unused by PE */
  Cpu_Interrupt,                        /*0x36  0xFF92   1  ivVReserved54 unused by PE */
  Cpu_Interrupt,                        /*0x35  0xFF94   1  ivVReserved53 unused by PE */
  Cpu_Interrupt,                        /*0x34  0xFF96   1  ivVReserved52 unused by PE */
  Cpu_Interrupt,                        /*0x33  0xFF98   1  ivVReserved51 unused by PE */
  Cpu_Interrupt,                        /*0x32  0xFF9A   1  ivVReserved50 unused by PE */
  Cpu_Interrupt,                        /*0x31  0xFF9C   1  ivVReserved49 unused by PE */
  Cpu_Interrupt,                        /*0x30  0xFF9E   1  ivVReserved48 unused by PE */
  Cpu_Interrupt,                        /*0x2F  0xFFA0   1  ivVemacec     unused by PE */
  Cpu_Interrupt,                        /*0x2E  0xFFA2   1  ivVemaclc     unused by PE */
  Cpu_Interrupt,                        /*0x2D  0xFFA4   1  ivVemacbrxerr unused by PE */
  Cpu_Interrupt,                        /*0x2C  0xFFA6   1  ivVemacrxbbo  unused by PE */
  Cpu_Interrupt,                        /*0x2B  0xFFA8   1  ivVemacrxbao  unused by PE */
  Cpu_Interrupt,                        /*0x2A  0xFFAA   1  ivVemacrxerr  unused by PE */
  Cpu_Interrupt,                        /*0x29  0xFFAC   1  ivVemacmii    unused by PE */
  Cpu_Interrupt,                        /*0x28  0xFFAE   1  ivVemacrxfc   unused by PE */
  Cpu_Interrupt,                        /*0x27  0xFFB0   1  ivVemactxc    unused by PE */
  Cpu_Interrupt,                        /*0x26  0xFFB2   1  ivVemacrxbbc  unused by PE */
  Cpu_Interrupt,                        /*0x25  0xFFB4   1  ivVemacrxbac  unused by PE */
  Cpu_Interrupt,                        /*0x24  0xFFB6   1  ivVephy       unused by PE */
  Cpu_Interrupt,                        /*0x23  0xFFB8   1  ivVflash      unused by PE */
  Cpu_Interrupt,                        /*0x22  0xFFBA   1  ivVReserved34 unused by PE */
  Cpu_Interrupt,                        /*0x21  0xFFBC   1  ivVReserved33 unused by PE */
  Cpu_Interrupt,                        /*0x20  0xFFBE   1  ivVReserved32 unused by PE */
  Cpu_Interrupt,                        /*0x1F  0xFFC0   1  ivViic        unused by PE */
  Cpu_Interrupt,                        /*0x1E  0xFFC2   1  ivVReserved30 unused by PE */
  Cpu_Interrupt,                        /*0x1D  0xFFC4   1  ivVcrgscm     unused by PE */
  Cpu_Interrupt,                        /*0x1C  0xFFC6   1  ivVcrgplllck  unused by PE */
  Cpu_Interrupt,                        /*0x1B  0xFFC8   1  ivVReserved27 unused by PE */
  Cpu_Interrupt,                        /*0x1A  0xFFCA   1  ivVportg      unused by PE */
  Cpu_Interrupt,                        /*0x19  0xFFCC   1  ivVporth      unused by PE */
  Cpu_Interrupt,                        /*0x18  0xFFCE   1  ivVportj      unused by PE */
  Cpu_Interrupt,                        /*0x17  0xFFD0   1  ivVReserved23 unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x16  0xFFD2   1  ivVatd        used by PE */
  Cpu_Interrupt,                        /*0x15  0xFFD4   1  ivVsci1       unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x14  0xFFD6   1  ivVsci0       used by PE */
  Cpu_Interrupt,                        /*0x13  0xFFD8   1  ivVspi        unused by PE */
  Cpu_Interrupt,                        /*0x12  0xFFDA   1  ivVtimpaie    unused by PE */
  Cpu_Interrupt,                        /*0x11  0xFFDC   1  ivVtimpaovf   unused by PE */
  Cpu_Interrupt,                        /*0x10  0xFFDE   1  ivVtimovf     unused by PE */
  Cpu_Interrupt,                        /*0x0F  0xFFE0   1  ivVtimch7     unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x0E  0xFFE2   1  ivVtimch6     used by PE */
  Cpu_Interrupt,                        /*0x0D  0xFFE4   1  ivVtimch5     unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x0C  0xFFE6   1  ivVtimch4     used by PE */
  Cpu_Interrupt,                        /*0x0B  0xFFE8   1  ivVReserved11 unused by PE */
  Cpu_Interrupt,                        /*0x0A  0xFFEA   1  ivVReserved10 unused by PE */
  Cpu_Interrupt,                        /*0x09  0xFFEC   1  ivVReserved9  unused by PE */
  Cpu_Interrupt,                        /*0x08  0xFFEE   1  ivVReserved8  unused by PE */
  Cpu_Interrupt,                        /*0x07  0xFFF0   1  ivVrti        unused by PE */
  Cpu_Interrupt,                        /*0x06  0xFFF2   1  ivVirq        unused by PE */
  Cpu_Interrupt,                        /*0x05  0xFFF4   -  ivVxirq       unused by PE */
  Cpu_Interrupt,                        /*0x04  0xFFF6   -  ivVswi        unused by PE */
  Cpu_Interrupt,                        /*0x03  0xFFF8   -  ivVtrap       unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x02  0xFFFA   -  ivVcop        unused by PE */
  (tIntFunc)0x00FFFFFFU,                /*0x01  0xFFFC   -  ivVclkmon     unused by PE */
  (tIntFunc)0x00FFFFFFU                 /*0x00  0xFFFE   -  ivVreset      used by PE */
};
/*lint -restore Enable MISRA rule (11.3) checking. */

#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_CPU_0 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_0)
{
  IntTable[0]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_1 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_1)
{
  IntTable[1]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_2 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_2)
{
  IntTable[2]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_3 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_3)
{
  IntTable[3]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_4 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_4)
{
  IntTable[4]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_5 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_5)
{
  IntTable[5]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_6 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_6)
{
  IntTable[6]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_7 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_7)
{
  IntTable[7]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_8 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_8)
{
  IntTable[8]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_9 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_9)
{
  IntTable[9]();                       /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_10 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_10)
{
  IntTable[10]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_11 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_11)
{
  IntTable[11]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_12 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_12)
{
  IntTable[12]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_13 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_13)
{
  IntTable[13]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_14 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_14)
{
  IntTable[14]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_15 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_15)
{
  IntTable[15]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_16 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_16)
{
  IntTable[16]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_17 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_17)
{
  IntTable[17]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_18 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_18)
{
  IntTable[18]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_19 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_19)
{
  IntTable[19]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_20 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_20)
{
  IntTable[20]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_21 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_21)
{
  IntTable[21]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_22 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_22)
{
  IntTable[22]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_23 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_23)
{
  IntTable[23]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_24 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_24)
{
  IntTable[24]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_25 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_25)
{
  IntTable[25]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_26 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_26)
{
  IntTable[26]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_27 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_27)
{
  IntTable[27]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_28 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_28)
{
  IntTable[28]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_29 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_29)
{
  IntTable[29]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_30 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_30)
{
  IntTable[30]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_31 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_31)
{
  IntTable[31]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_32 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_32)
{
  IntTable[32]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_33 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_33)
{
  IntTable[33]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_34 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_34)
{
  IntTable[34]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_35 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_35)
{
  IntTable[35]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_36 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_36)
{
  IntTable[36]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_37 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_37)
{
  IntTable[37]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_38 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_38)
{
  IntTable[38]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_39 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_39)
{
  IntTable[39]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_40 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_40)
{
  IntTable[40]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_42 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_42)
{
  IntTable[42]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_44 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_44)
{
  IntTable[44]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_45 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_45)
{
  IntTable[45]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_46 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_46)
{
  IntTable[46]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_47 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_47)
{
  IntTable[47]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_48 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_48)
{
  IntTable[48]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_50 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_50)
{
  IntTable[50]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_52 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_52)
{
  IntTable[52]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_53 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_53)
{
  IntTable[53]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_54 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_54)
{
  IntTable[54]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_55 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_55)
{
  IntTable[55]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_56 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_56)
{
  IntTable[56]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_57 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_57)
{
  IntTable[57]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_58 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_58)
{
  IntTable[58]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_59 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_59)
{
  IntTable[59]();                      /* Invoke an user routine */
}

/*
** ===================================================================
**     Method      :  Cpu_CPU_60 (component MC9S12NE64_112)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
ISR(CPU_60)
{
  IntTable[60]();                      /* Invoke an user routine */
}


/*
** ===================================================================
**     Method      :  Cpu_Delay100US (component MC9S12NE64_112)
**
**     Description :
**         This method realizes software delay. The length of delay
**         is at least 100 microsecond multiply input parameter
**         [us100]. As the delay implementation is not based on real
**         clock, the delay time may be increased by interrupt
**         service routines processed during the delay. The method
**         is independent on selected speed mode.
**     Parameters  :
**         NAME            - DESCRIPTION
**         us100           - Number of 100 us delay repetitions.
**                         - The value of zero results in maximal 
**                           delay of approx. 6.5 seconds.
**     Returns     : Nothing
** ===================================================================
*/
#pragma NO_ENTRY                       /* Suppress generation of entry code in a function */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
#pragma MESSAGE DISABLE C5703          /*Disable C5703: Parameter ‘<Parameter>’ declared in function ‘<Function>’ but not referenced */
void Cpu_Delay100US(word us100)
{
  /* irremovable overhead (ignored): 13 cycles */
  /* ldd:  2 cycles overhead (load parameter into register) */
  /* jsr:  4 cycles overhead (call this function) */
  /* rts:  7 cycles overhead (return from this function) */

  /* irremovable overhead for each 100us cycle (counted): 13 cycles */
  /* dbne:  3 cycles overhead (return from this function) */

  /*lint -save  -e950 -e522 Disable MISRA rule (1.1,14.2) checking. */
  asm {
    loop:
    /* 100 us delay block begin */
    /*
     * Delay
     *   - requested                  : 100 us @ 25MHz,
     *   - possible                   : 2500 c, 100000 ns
     *   - without removable overhead : 2497 c, 99880 ns
     */
    pshd                               /* (2 c: 80 ns) backup D */
    ldd #$033E                         /* (2 c: 80 ns) number of iterations */
    label0:
    dbne d, label0                     /* (3 c: 120 ns) repeat 830x */
    puld                               /* (3 c: 120 ns) restore D */
    /* 100 us delay block end */
    dbne d, loop                       /* us100 parameter is passed via D register */
    rts                                /* return from subroutine */
  };
  /*lint -restore Enable MISRA rule (1.1,14.2) checking. */
}

#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12NE64_112)
**
**     Description :
**         The method services the interrupt of the peripheral(s) not 
**         used by Processor Expert.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Cpu_Interrupt(void)
{
  /*lint -save -e950 Disable MISRA rule (1.1) checking. */
  asm(BGND);
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12NE64_112)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12NE64_112)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12NE64_112)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12NE64_112)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_GetIntVect (component MC9S12NE64_112)
**
**     Description :
**         Return address of interrupt vector service routine. This
**         method can be generated only if the interrupt vector
**         table is generated into RAM (see options).
**     Parameters  :
**         NAME            - DESCRIPTION
**         VectNo          - Interrupt vector number
**       * ProcAddr        - Address of the interrupt
**                           handler
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Vector number is out of
**                           range.
** ===================================================================
*/
byte Cpu_GetIntVect(word VectNo,tIntFunc *ProcAddr)
{
  if (VectNo < 64U) {                  /* Is number of vector valid? */
    *ProcAddr = IntTable[VectNo];      /* Result address of the given service routine */
    return ERR_OK;                     /* OK */
  }
  else {
    return ERR_RANGE;                  /* If no then error */
  }
}

/*
** ===================================================================
**     Method      :  Cpu_SetIntVect (component MC9S12NE64_112)
**
**     Description :
**         Set interrupt vector service routine. This method can be
**         generated only if the interrupt vector table is generated
**         into RAM (see options).
**     Parameters  :
**         NAME            - DESCRIPTION
**         VectNo          - Number of interrupt vector
**       * ProcAddr        - Address of the new interrupt
**                           handler
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Vector number is out of
**                           range.
**                           ERR_VALUE - Vector is used by Processor Expert
**                           and cannot be handled by this method.
** ===================================================================
*/
byte Cpu_SetIntVect(word VectNo,tIntFunc ProcAddr)
{
  /*lint -save  -e923 Disable MISRA rule (11.3) checking. */
  if ((word)IntTable[VectNo]==0xFFFFU) { /* Is given number of vector shared with any component in PE? If yes then error */
    return ERR_VALUE;
  }
  /*lint -restore Enable MISRA rule (11.3) checking. */
  if (VectNo < 64U) {                  /* Is number of vector valid? */
    EnterCritical();                   /* Enter the critical section */
    IntTable[VectNo] = ProcAddr;       /* Set address of new service routine */
    ExitCritical();                    /* Exit the critical section */
    return ERR_OK;                     /* OK */
  }
  else {
    return ERR_RANGE;                  /* If no then error */
  }
}

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12NE64_112)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */
#pragma CODE_SEG __NEAR_SEG NON_BANKED

#define INITRG_ADR  0x11U              /* Register map position register */

#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{
  /* ### MC9S12NE64_112 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Initialization of the registers INITRG, INITRM, INITEE is done to protect them to be written accidentally later by the application */
  /*lint -save  -e950 -e923 Disable MISRA rule (1.1,11.3) checking. */
  *(byte*)INITRG_ADR = 0x00U;          /* Set the register map position */
  asm("nop");                          /* nop instruction */
  /*lint -restore Enable MISRA rule (1.1,11.3) checking. */
  /* INITRM: RAM15=0,RAM14=0,RAM13=1,RAM12=0,RAM11=1,??=0,??=0,RAMHAL=1 */
  setReg8(INITRM, 0x29U);              /* Set the RAM map position */ 
  /* MISC: ??=0,??=0,??=0,??=0,EXSTR1=1,EXSTR0=1,ROMHM=0,ROMON=1 */
  setReg8(MISC, 0x0DU);                 
  /* PEAR: NOACCE=0,??=0,PIPOE=0,NECLK=1,LSTRE=0,RDWE=0,??=0,??=0 */
  setReg8(PEAR, 0x10U);                 
  /*  System clock initialization */
  /* CLKSEL: PLLSEL=0,PSTP=0,SYSWAI=0,ROAWAI=0,PLLWAI=0,CWAI=0,RTIWAI=0,COPWAI=0 */
  setReg8(CLKSEL, 0x00U);              /* Select clock source from XTAL and set bits in CLKSEL reg. */ 
  /* PLLCTL: CME=1,PLLON=0,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xB1U);              /* Disable the PLL */ 
  /* SYNR: ??=0,??=0,SYN5=0,SYN4=0,SYN3=0,SYN2=0,SYN1=0,SYN0=0 */
  setReg8(SYNR, 0x00U);                /* Set the multiplier register */ 
  /* REFDV: ??=0,??=0,??=0,??=0,REFDV3=0,REFDV2=0,REFDV1=0,REFDV0=0 */
  setReg8(REFDV, 0x00U);               /* Set the divider register */ 
  /* PLLCTL: CME=1,PLLON=1,AUTO=1,ACQ=1,??=0,PRE=0,PCE=0,SCME=1 */
  setReg8(PLLCTL, 0xF1U);               
  while(CRGFLG_LOCK == 0U) {           /* Wait until the PLL is within the desired tolerance of the target frequency */
  }
  /* CLKSEL: PLLSEL=1 */
  setReg8Bits(CLKSEL, 0x80U);          /* Select clock source from PLL */ 
  /*** End of PE initialization code after reset ***/
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12NE64_112)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* PTL: PTL6=0,PTL5=0,PTL4=0,PTL3=0,PTL2=0,PTL1=0,PTL0=0 */
  clrReg8Bits(PTL, 0x7FU);              
  /* WOML: WOML6=0,WOML5=0,WOML4=0,WOML3=0,WOML2=0,WOML1=0,WOML0=0 */
  clrReg8Bits(WOML, 0x7FU);             
  /* DDRL: DDRL6=1,DDRL5=1,DDRL4=1,DDRL3=1,DDRL2=1,DDRL1=1,DDRL0=1 */
  setReg8Bits(DDRL, 0x7FU);             
  /* PORTA: BIT2=0,BIT1=0,BIT0=0 */
  clrReg8Bits(PORTA, 0x07U);            
  /* PUCR: PUPEE=0,PUPAE=0 */
  clrReg8Bits(PUCR, 0x11U);             
  /* DDRA: BIT2=1,BIT1=1,BIT0=1 */
  setReg8Bits(DDRA, 0x07U);             
  /* PIEH: PIEH6=0 */
  clrReg8Bits(PIEH, 0x40U);             
  /* PPSH: PPSH6=0 */
  clrReg8Bits(PPSH, 0x40U);             
  /* PERH: PERH6=1 */
  setReg8Bits(PERH, 0x40U);             
  /* DDRH: DDRH6=0 */
  clrReg8Bits(DDRH, 0x40U);             
  /* PPSS: PPSS1=0,PPSS0=0 */
  clrReg8Bits(PPSS, 0x03U);             
  /* PERS: PERS1=1,PERS0=1 */
  setReg8Bits(PERS, 0x03U);             
  /* WOMS: WOMS6=0,WOMS5=0,WOMS4=0,WOMS1=0 */
  clrReg8Bits(WOMS, 0x72U);             
  /* RDRS: RDRS7=0,RDRS6=0,RDRS5=0,RDRS4=0,RDRS3=0,RDRS2=0,RDRS1=0,RDRS0=0 */
  setReg8(RDRS, 0x00U);                 
  /* TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0 */
  clrReg8Bits(TSCR1, 0xF0U);            
  /* PACTL: CLK1=0,CLK0=0 */
  clrReg8Bits(PACTL, 0x0CU);            
  /* OC7M: OC7M6=0,OC7M4=0 */
  clrReg8Bits(OC7M, 0x50U);             
  /* TIOS: IOS6=1,IOS4=1 */
  setReg8Bits(TIOS, 0x50U);             
  /* TCTL1: OM6=0,OL6=0,OM4=0,OL4=0 */
  clrReg8Bits(TCTL1, 0x33U);            
  /* TTOV: TOV6=0,TOV4=0 */
  clrReg8Bits(TTOV, 0x50U);             
  /* TSCR2: TCRE=0,PR2=1,PR1=1,PR0=0 */
  clrSetReg8Bits(TSCR2, 0x09U, 0x06U);  
  /* TFLG1: C7F=1,C6F=1,C5F=1,C4F=1,??=1,??=1,??=1,??=1 */
  setReg8(TFLG1, 0xFFU);                
  /* TIE: C6I=1,C4I=1 */
  setReg8Bits(TIE, 0x50U);              
  /* PEAR: PIPOE=0,NECLK=1 */
  clrSetReg8Bits(PEAR, 0x20U, 0x10U);   
  /* PORTE: BIT5=0,BIT4=0 */
  clrReg8Bits(PORTE, 0x30U);            
  /* DDRE: BIT5=1,BIT4=1 */
  setReg8Bits(DDRE, 0x30U);             
  /* CRGINT: LOCKIE=0,SCMIE=0 */
  clrReg8Bits(CRGINT, 0x12U);           
  /* COPCTL: WCOP=0,RSBCK=0,??=0,??=0,??=0,CR2=0,CR1=0,CR0=0 */
  setReg8(COPCTL, 0x00U);               
  /* RDRIV: RDPK=0,RDPE=1,RDPB=0,RDPA=0 */
  clrSetReg8Bits(RDRIV, 0x83U, 0x10U);  
  /* RDRH: RDRH6=0,RDRH5=0,RDRH4=0,RDRH3=0,RDRH2=0,RDRH1=0,RDRH0=0 */
  clrReg8Bits(RDRH, 0x7FU);             
  /* RDRJ: RDRJ7=0,RDRJ6=0,RDRJ3=0,RDRJ2=0,RDRJ1=0,RDRJ0=0 */
  clrReg8Bits(RDRJ, 0xCFU);             
  /* RDRT: RDRT7=0,RDRT6=0,RDRT5=0,RDRT4=0 */
  clrReg8Bits(RDRT, 0xF0U);             
  /* RDRL: RDRL6=0,RDRL5=0,RDRL4=0,RDRL3=0,RDRL2=0,RDRL1=0,RDRL0=0 */
  clrReg8Bits(RDRL, 0x7FU);             
  /* RDRG: RDRG7=0,RDRG6=0,RDRG5=0,RDRG4=0,RDRG3=0,RDRG2=0,RDRG1=0,RDRG0=0 */
  setReg8(RDRG, 0x00U);                 
  /* INTCR: IRQEN=0 */
  clrReg8Bits(INTCR, 0x40U);            
  /* ### MC9S12NE64_112 "Cpu" init code ... */
  Cpu_OnReset();
  /* ### BitsIO "leds" init code ... */
  /* ### BitsIO "rgbled" init code ... */
  /* ### BitIO "sw1" init code ... */
  /* ### Init_SCI "uart0" init code ... */
  uart0_Init();
  /* ### Init_ADC "ADC1" init code ... */
  ADC1_Init();
  /* ### TimerInt "slow_timer" init code ... */
  /* TC4: BIT15=1,BIT14=0,BIT13=0,BIT12=1,BIT11=1,BIT10=0,BIT9=0,BIT8=0,BIT7=1,BIT6=0,BIT5=0,BIT4=1,BIT3=0,BIT2=1,BIT1=1,BIT0=0 */
  setReg16(TC4, 0x9896U);              /* Store given value to the compare register */ 
  /* ### TimerInt "fast_timer" init code ... */
  /* TC6: BIT15=0,BIT14=0,BIT13=0,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=0,BIT7=0,BIT6=0,BIT5=1,BIT4=0,BIT3=0,BIT2=1,BIT1=1,BIT0=1 */
  setReg16(TC6, 0x27U);                /* Store given value to the compare register */ 
  /* ### BitIO "rf_ce" init code ... */
  /* ### BitIO "rf_nss" init code ... */
  /* ### BitIO "rf_irq" init code ... */
  /* ### Init_SPI "SPI1" init code ... */
  SPI1_Init();
  /* Common peripheral initialization - ENABLE */
  /* TSCR1: TEN=1 */
  setReg8Bits(TSCR1, 0x80U);            
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
