/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : fast_timer.h
**     Project   : Project_2
**     Processor : MC9S12NE64CPV
**     Component : TimerInt
**     Version   : Component 02.159, Driver 01.20, CPU db: 2.87.134
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2013-12-02, 12:18
**     Abstract  :
**         This component "TimerInt" implements a periodic interrupt.
**         When the component and its events are enabled, the "OnInterrupt"
**         event is called periodically with the period that you specify.
**         TimerInt supports also changing the period in runtime.
**         The source of periodic interrupt can be timer compare or reload
**         register or timer-overflow interrupt (of free running counter).
**     Settings  :
**         Timer name                  : TIM_Counter (16-bit)
**         Compare name                : TC6
**         Counter shared              : Yes
**
**         High speed mode
**             Prescaler               : divide-by-64
**             Clock                   : 390625 Hz
**           Initial period/frequency
**             Xtal ticks              : 2496
**             microseconds            : 100
**             seconds (real)          : 0.00009984
**             Hz                      : 10016
**             kHz                     : 10
**
**         Runtime setting             : none
**
**         Initialization:
**              Timer                  : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : TCNT      [$0044]
**              Mode                   : TIOS      [$0040]
**              Run                    : TSCR1     [$0046]
**              Prescaler              : TSCR2     [$004D]
**
**         Compare registers
**              Compare                : TC6       [$005C]
**
**         Flip-flop registers
**              Mode                   : TCTL1     [$0048]
**     Contents  :
**         No public methods
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __fast_timer
#define __fast_timer

/* MODULE fast_timer. */

#include "Cpu.h"


#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void fast_timer_Interrupt(void);
/*
** ===================================================================
**     Method      :  fast_timer_Interrupt (component TimerInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma CODE_SEG DEFAULT

/* END fast_timer. */

#endif /* ifndef __fast_timer */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
