/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : rf_nss.h
**     Project   : Project_2
**     Processor : MC9S12NE64CPV
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.15, CPU db: 2.87.134
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2017-03-27, 17:06
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       41            |  PE4_ECLK
**             ----------------------------------------------------
**
**         Port name                   : E
**
**         Bit number (in port)        : 4
**         Bit mask of the port        : $0010
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0
**         Initial pull option         : off
**
**         Port data register          : PORTE     [$0008]
**         Port control register       : DDRE      [$0009]
**         Port function register      : INTCR     [$001E]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool rf_nss_GetVal(void);
**         PutVal - void rf_nss_PutVal(bool Val);
**         ClrVal - void rf_nss_ClrVal(void);
**         SetVal - void rf_nss_SetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef rf_nss_H_
#define rf_nss_H_

/* MODULE rf_nss. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG rf_nss_CODE
/*
** ===================================================================
**     Method      :  rf_nss_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define rf_nss_GetVal() ( \
    (bool)((getReg8(PORTE) & 0x10U))   /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  rf_nss_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void rf_nss_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  rf_nss_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define rf_nss_ClrVal() ( \
    (void)clrReg8Bits(PORTE, 0x10U)    /* BIT4=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  rf_nss_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define rf_nss_SetVal() ( \
    (void)setReg8Bits(PORTE, 0x10U)    /* BIT4=0x01U */ \
  )

#pragma CODE_SEG DEFAULT

/* END rf_nss. */
#endif /* #ifndef __rf_nss_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
