/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : rgbled.c
**     Project   : Project_2
**     Processor : MC9S12NE64CPV
**     Component : BitsIO
**     Version   : Component 02.102, Driver 03.14, CPU db: 2.87.134
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2013-12-02, 12:18
**     Abstract  :
**         This component "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This component is set to work in Output direction only.
**     Settings  :
**         Port name                   : A
**
**         Bit mask of the port        : $0007
**         Number of bits/pins         : 3
**         Single bit numbers          : 0 to 2
**         Values range                : 0 to 7
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : PORTA     [$0000]
**         Port control register       : DDRA      [$0002]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    60   |   PA0_ADDR8_DATA8
**                    1      |    61   |   PA1_ADDR9_DATA9
**                    2      |    62   |   PA2_ADDR10_DATA10
**             ----------------------------------------------------
**
**         Optimization for            : speed
**     Contents  :
**         PutVal - void rgbled_PutVal(byte Val);
**         PutBit - void rgbled_PutBit(byte Bit, bool Val);
**         SetBit - void rgbled_SetBit(byte Bit);
**         ClrBit - void rgbled_ClrBit(byte Bit);
**         NegBit - void rgbled_NegBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE rgbled. */

#include "rgbled.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG rgbled_DATA           /* Select data segment "rgbled_DATA" */
#pragma CODE_SEG rgbled_CODE
#pragma CONST_SEG rgbled_CONST         /* Constant section for this module */
/*
** ===================================================================
**     Method      :  rgbled_GetMsk (component BitsIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte rgbled_Table[3U] = { /* Table of mask constants */
   0x01U, 0x02U, 0x04U
};

static byte rgbled_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<3U) ? rgbled_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  rgbled_PutVal (component BitsIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val        - Output value (0 to 7)
**     Returns     : Nothing
** ===================================================================
*/
void rgbled_PutVal(byte Val)
{
  Val &= 0x07U;                        /* Mask output value */
  setReg8(PORTA, (getReg8(PORTA) & (byte)(~(byte)0x07U)) | Val); /* Put masked value on port */
}

/*
** ===================================================================
**     Method      :  rgbled_PutBit (component BitsIO)
**
**     Description :
**         This method writes the new value to the specified bit
**         of the output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit (0 to 2)
**         Val        - New value of the bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
**     Returns     : Nothing
** ===================================================================
*/
void rgbled_PutBit(byte Bit, bool Val)
{
  byte const Mask = rgbled_GetMsk(Bit); /* Temporary variable - put bit mask */
  if (Val) {
    setReg8Bits(PORTA, Mask);          /* [bit (Bit)]=0x01U */
  } else { /* !Val */
    clrReg8Bits(PORTA, Mask);          /* [bit (Bit)]=0x00U */
  } /* !Val */
}

/*
** ===================================================================
**     Method      :  rgbled_ClrBit (component BitsIO)
**
**     Description :
**         This method clears (sets to zero) the specified bit
**         of the output value.
**         [ It is the same as "PutBit(Bit,FALSE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to clear (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
void rgbled_ClrBit(byte Bit)
{
  byte const Mask = rgbled_GetMsk(Bit); /* Temporary variable - set bit mask */
  clrReg8Bits(PORTA, Mask);            /* [bit (Bit)]=0x00U */
}

/*
** ===================================================================
**     Method      :  rgbled_SetBit (component BitsIO)
**
**     Description :
**         This method sets (sets to one) the specified bit of the
**         output value.
**         [ It is the same as "PutBit(Bit,TRUE);" ]
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to set (0 to 2)
**     Returns     : Nothing
** ===================================================================
*/
void rgbled_SetBit(byte Bit)
{
  byte const Mask = rgbled_GetMsk(Bit); /* Temporary variable - set bit mask */
  setReg8Bits(PORTA, Mask);            /* [bit (Bit)]=0x01U */
}

/*
** ===================================================================
**     Method      :  rgbled_NegBit (component BitsIO)
**
**     Description :
**         This method negates (inverts) the specified bit of the
**         output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to invert (0 to 31)
**     Returns     : Nothing
** ===================================================================
*/
void rgbled_NegBit(byte Bit)
{
  byte const Mask = rgbled_GetMsk(Bit); /* Temporary variable - set bit mask */
  invertReg8Bits(PORTA, Mask);         /* [bit (Bit)]=invert */
}


/* END rgbled. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
