/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : uart0.c
**     Project   : Project_2
**     Processor : MC9S12NE64CPV
**     Component : Init_SCI
**     Version   : Component 01.075, Driver 01.09, CPU db: 2.87.134
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 2017-03-27, 17:01
**     Abstract  :
**          This file implements the SCI (SCI0) module initialization
**          according to the Peripheral Initialization Component settings,
**          and defines interrupt service routines prototypes.
**          The SCI includes these distinctive features:
**          • Full-duplex operation
**          • Standard mark/space non-return-to-zero (NRZ) format
**          • Selectable IrDA 1.4 return-to-zero-inverted (RZI) format
**          with programmable pulse widths
**          • 13-bit baud rate selection
**          • Programmable 8-bit or 9-bit data format
**          • Separately enabled transmitter and receiver
**          • Programmable transmitter output parity
**          • Two receiver wakeup methods:
**          – Idle line wakeup
**          – Address mark wakeup
**          • Interrupt-driven operation with eight flags:
**          – Transmitter empty
**          – Transmission complete
**          – Receiver full
**          – Idle receiver input
**          – Receiver overrun
**          – Noise error
**          – Framing error
**          – Parity error
**          • Receiver framing error detection
**          • Hardware parity checking
**          • 1/16 bit-time noise detection
**     Settings  :
**          Component name                                 : uart0
**          Device                                         : SCI0
**          Settings
**            Clock setting
**              Baud rate divisor                          : 13
**              Baud rate                                  : 120192.3 Bd
**            Loop mode                                    : Disabled
**            Break character length                       : 10 or 11 bits
**            Receiver wake up mode                        : normal operation
**            Wake up                                      : by idle line
**            Idle Line counting                           : After start bit
**            Stop in Wait mode                            : no
**            Parity                                       : none
**            Data format                                  : 8 bits
**            Infrared module                              : Disabled
**            Transmitter Narrow Pulse                     : 3/16
**          Pins
**            RxD pin                                      : PS0_SCI0_RXD
**            RxD pin signal                               : 
**            TxD pin                                      : PS1_SCI0_TXD
**            TxD pin signal                               : 
**          Interrupts
**            Interrupt                                    : Vsci0
**            Receiver full interrupt                      : Enabled
**            Transmitter empty interrupt                  : Disabled
**            Transmitter complete interrupt               : Disabled
**            Idle Line interrupt                          : Disabled
**            Interrupt priority                           : 1
**            ISR name                                     : uart0_rx
**          Initialization
**            Call Init in CPU init. code                  : yes
**            Transmitter                                  : Enabled
**            Receiver                                     : Enabled
**     Contents  :
**         Init - void uart0_Init(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE uart0. */

#include "uart0.h"

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Project_2.c
**      Events.c
**
** ###################################################################
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(uart0_rx)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      The ISR is invoked by TDRE, TC, RDRF or IDLE flag. The TDRE and TC flag is cleared
        //      if SCISR1 register is read  and any data are written to SCIDRL register.
        //      The RDRF and IDLE flag is cleared if SCISR1 register is read  and SCIDRL register
        //      is read.
        }
#pragma CODE_SEG DEFAULT
*/
/*
** ===================================================================
**     Method      :  uart0_Init (component Init_SCI)
**
**     Description :
**         This method initializes registers of the SCI module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void uart0_Init(void)
{
  /* SCI0CR2: SCTIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  setReg8(SCI0CR2, 0x00U);             /* Disable the SCI0 module */ 
  (void)getReg8(SCI0SR1);              /* Dummy read of the SCI0SR1 registr to clear flags */
  (void)getReg8(SCI0DRL);              /* Dummy read of the SCI0DRL registr to clear flags */
  /* SCI0SR2: ??=0,??=0,??=0,??=0,??=0,BRK13=0,TXDIR=0,RAF=0 */
  setReg8(SCI0SR2, 0x00U);              
  /* SCI0BD: IREN=0,TNP1=0,TNP0=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0,SBR7=0,SBR6=0,SBR5=0,SBR4=0,SBR3=1,SBR2=1,SBR1=0,SBR0=1 */
  setReg16(SCI0BD, 0x0DU);              
  /* SCI0CR1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  setReg8(SCI0CR1, 0x00U);              
  /* SCI0CR2: SCTIE=0,TCIE=0,RIE=1,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
  setReg8(SCI0CR2, 0x2CU);              
}

/* END uart0. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
